### ISSUE TITLE
No helper functions

### ISSUE THREAD

**Issue by Behinder** [stevetweeddale/gatsby-source-git#13]
When you are writing documentation please be specific. I cannot find anywhere on internet information what to put in `gatsby-node.js` configuration file.

`const { createFilePath } = require(`gatsby-source-filesystem`)` on top will not work as your plugin do not contain createFilePath helper function, so saying "it should work same way as git-source-filesystem' is an overstatement.

**Comment by CanRau** [comment]
I guess it's same in sourcing, not necessarily in creating as it's a source plugin. The filesystem one provides this helper for convenience. 🤔

Not everyone is using `createFilePath` at least I'm not and if I needed it I can get it from `gatsby-source-filesystem`.

**Comment by Behinder** [comment]
So what declaration should I put in Gatsby-node.js?
Just require(‘Gatsby-source-git’) ??

This is confusing for me as I don’t see code example, just example of
GraphQL query but I have to build nodes both from git and from local file
system.

**Comment by stevetweeddale** [comment]
Hi @Behinder! When writing support requests to strangers, please try to sound friendly 😄 

Here's what the readme actually says:

>[gatsby-source-git] sucks the files into the graph as `File` nodes, as if you'd configured gatsby-source-filesystem on that directory. As such, all the transformer plugins that operate on files should work exactly as they do with gatsby-source-filesystem

Which isn't the same thing as saying "this plugin is a drop-in replacement for `gatsby-source-filesystem` and shares every aspect of its API" (which would indeed be an overstatement). As @CanRau mentioned, this is a source plugin, so its job is to get nodes into the graph. Specifically, it puts nodes that look just like the ones created by `gatsby-source-filesystem`.

Now `gatsby-source-filesystem` then also includes the `createFilePath` helper as a convenience for later on in the process, as often people want to create a pretty URL from a filesystem path when programmatically creating pages from graph nodes. I didn't bundle a copy of that function in this plugin because it's nothing to do with sourcing, and I don't want to maintain a fork of something that's already in the main gatsby repo. If you need that helper, then include it like so:

```js
const { createFilePath } = require(`gatsby-source-filesystem`)
```

Hope that clears things up for you!

**Comment by CanRau** [comment]
You create the pages like with most other source plugins, following the example in https://www.gatsbyjs.org/tutorial/part-seven/
You change the query from MarkdownRemark to that of the source plugin.

**Comment by Behinder** [comment]
It is difficult to “sound” in writing 😊 thanks for that explanation, it
would help if such explanations be put into documentation as it is often
confusing to see just code example and I usually lost interest in plugins I
cannot understand 😁
Gatsby-source-filesystem is also source plugin so it was valid assumption
git plugin is meant to replace it to fetching content from different source
than local.

But never mind , to not sound unfriendly I try to not sound at all and stop
commenting :)

**Comment by stevetweeddale** [comment]
I've updated the readme to hopefully reduce the likelihood of the same confusion going forwards. Thanks everyone!
