### ISSUE TITLE
What's preventing private repos?

### ISSUE THREAD

**Issue by CanRau** [stevetweeddale/gatsby-source-git#4]
Hey, thanks for this handy source plugin 🙏 
Just stumbled upon it and it could replace my hacky GitLab solution, yet my repo is private..
I tried to just provide it with
```
https://gitlab.com:<personal_access_token>@gitlab.com/user/repo.git
```
replaced the token, user and repo name of course and it's sourcing for a pretty long time, mostly because my internet is slow, anyway it's doing something, ~~yet the `.cache/caches/gatsby-source-git` dir stays empty~~ just found out it's all in `.cache/gatsby-source-git` still no nodes are available in my graphiql
You've wrote it wouldn't be hard to support it, my first peeks into the code didn't unveiled anything obvious to me 🤓 
If you've got a hint for me, I might be able to prepare a PR..

Edit: or I just use a small package.json or shell script to clone the repo 🤔 

Update: got it working combining it with `gatsby-source-filesystem` right after `gatsby-source-git` something is preventing the node creation?! 🤔 
I'm a little lazy digging more into debugging cause my internet is pretty slow, maybe I could copy paste the cloned repo back in after every change 🤔 

**Update**: Okay so it might be due to my wacky internet connection or out dated mashine, something seems odd locally..on Netlify's CI the aforementioned solution just generated duplicate content, from the git and fs sources 🤦‍♂️ so using git online and fs locally seems to be my goto for now..

Thanks for the plugin, closing because it's working for me with a private GitLab repo now

**Comment by infinitecompute** [comment]
The Readme says "Only public repositories are supported right now. But a PR should be simple enough if you want that."  @CanRau it sounds like you got this working just by using the ```personal_access_token```?

**Comment by CanRau** [comment]
@infinitecompute exactly

```js
{
  resolve: `gatsby-source-git`,
  options: {
    name: `gaiama-content`,
    remote: `https://gitlab.com:${GAIAMA_CONTENT_TOKEN}@gitlab.com/gaiama/content.git`,
  },
}
```
works like a charm 👍 

Any issues?

**Comment by infinitecompute** [comment]
Thanks @CanRau CanRau.  This worked just fine.  I'll suggest an update to the README.

**Comment by BrunoBoehm** [comment]
Hi all, actually even without the token, I'm able to access my github private repo... strange: would that be because my git is already signed in, or has anyone made an update to the plugin since the above discussion?

**Comment by stevetweeddale** [comment]
@BrunoBoehm yeah this plugin just calls the git binary installed on your machine as if you were calling it yourself on the command line. So if you've got ssh keys set up, then git will still use them. However, you probably want your site to build on other machines as well without the requirement that ssh keys will be set up (a Netlify build for example).

@CanRau is using a Gitlab feature which allows you to clone your repo from a URL with a special authentication token (generated in GitLab) in it, which bypasses the need for any other authentication mechanism (eg SSH or command line prompt). GitHub has a similar feature, called [Personal Access Tokens](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line), which would allow you to clone a repo with a URL like:

`https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}`

@CanRau thanks for writing up your experiences with this! I think when I originally wrote the README I vaguely anticipated providing some kind of nice way for a user to provide credentials that the plugin would use, probably in the config object (eg separate user and password fields). But the reality is that "access tokens in the URL" seems to be pretty much the defacto way git hosts support this kind of use-case, so I should probably just update the readme to give people to some pointers to that effect.

And as an unrelated aside, you mentioned that your internet connectivity is bad – I've been doing the following to avoid downloading a massive repo every time the gatsby cache gets cleared:

I've got [these lines at the bottom of gatsby-config.js](https://github.com/Alfresco/builder-network/blob/02ebc5965154bcc56999a284ebeb9034602dc183/gatsby-config.js#L127-L129). I've then told git to ignore `gatsby-config.local.js`, and have something like the following in it only on my local machine:

```
module.exports = gatsbyConfig => {
  gatsbyConfig.plugins.map(plugin => {
    if (plugin.resolve === "gatsby-source-git" && plugin.options.name === "<big repo>") {
      // Override the remote with a filepath pointing to a local clone of your repo.
      plugin.options.remote = `/path/to/local/clone`
    }
    return plugin
  })
  return gatsbyConfig
}
```

That way, the clones that the plugin does are just local ones rather than over the network. Obviously you only then get upstream changes if you manually pull them into that local clone, but it's handy if cloning is a pain!

**Comment by CanRau** [comment]
Interesting, that'd work too.
I switch to `gatsby-source-filesystem` locally, works great 👍

**Comment by stevetweeddale** [comment]
Yeah, that should broadly work too! The only issue I can see you running into would be if you were to start using the `gitRemote` field `gatsby-source-git` adds to the nodes. But the `File` nodes should be otherwise the same, so should work fine.

I do it the optional-local-override-file way because I don't like juggling local modifications that I don't intend to commit/push!

**Comment by CanRau** [comment]
Interesting, true. So far didn't have any issues 🤠
