### ISSUE TITLE
Cloning part of the remote repo

### ISSUE THREAD

**Issue by BrunoBoehm** [stevetweeddale/gatsby-source-git#9]
Hi there, 
I'm cloning a pretty huge repo from github, from which I only need one specific folder called 'content/articles/'. I can see the `patterns` fast-glob is telling which files to process and create as nodes, but at this stage all of my unnecessary content is already imported into the `.cache`. Is there a built-in solution in your plugin for a selective cloning of the remote repo?
Thanks!

**Comment by stevetweeddale** [comment]
Yeah big repos are still a bit painful. We do a shallow clone (eg. with `--depth 1`) so it only downloads the latest objects rather than the full repo history. But that still doesn't help when there's just a lot of big files in the latest version.

As we just use git directly, we can only do what git supports. While it does now have a [partial clone feature](https://git-scm.com/docs/partial-clone), it isn't very widely supported by git hosting providers yet, so it's probably not worth trying support at the moment. It's certainly something to keep an eye on though as it becomes more widely available.

**Comment by stevetweeddale** [comment]
I'm going to close this one out for now, as I'm not planning on implementing this until partial cloning has widespread support from the main hosting providers and I'd rather keep things tidy in the meantime!
